apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions-cronjob
  labels:
    app: django-app
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
          - name: django-clearsessions
            image: django_app:latest
            command: ["python", "manage.py", "clearsessions"]
            envFrom:
              - configMapRef:
                  name: django-config-map
            imagePullPolicy: Never
          restartPolicy: Never