apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config-map
  labels:
    env: prod
data:
  DEBUG: "False"
  SECRET_KEY: "1234"
  DATABASE_URL: "postgres://test_k8s:OwOtBep9Frut@192.168.243.199:5432/test_k8s"
  ALLOWED_HOSTS: "star-burger.test"