apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config-map-prod
  labels:
    env: prod
data:
  DEBUG: "True"
  SECRET_KEY: "1234"
  DATABASE_URL: "postgres://test_k8s:OwOtBep9Frut@postgresql:6432/test_k8s"
  ALLOWED_HOSTS: "edu-evil-panini.sirius-k8s.dvmn.org"