kind: Service
apiVersion: v1
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: django-app
  type: ClusterIP