apiVersion : apps/v1
kind : Deployment
metadata :
  name : django-deployment
  labels :
    app : django-app
spec :
  selector :
    matchLabels :
      project : django-app
  template :
    metadata :
      labels :
        project : django-app
    spec :
      containers :
        - name : django-app
          image : atmoslayer/django_app:latest
          envFrom :
            - configMapRef :
                name : django-config-map-prod
          ports :
            - containerPort : 80

---

apiVersion : v1
kind : Service
metadata :
  name : django-service
  labels :
    env : prod
spec :
  selector :
    project : django-app
  ports :
    - name : django-listener
      port : 80
      targetPort : 80
      nodePort: 30331
      protocol : TCP
  type : NodePort
