kind: Pod
apiVersion: v1
metadata:
  name: django-app
  labels:
    run: django-app
spec:
  containers:
    - name: django-app
      image: django_app:latest
      env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: django-config-map
              key: database_url
        - name: SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: django-config-map
              key: secret_key
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: django-config-map
              key: debug
        - name: ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: django-config-map
              key: allowed_hosts
      imagePullPolicy: Never
      ports:
        - containerPort: 80